import { Container } from '@/components/Container'
import { Header } from '@/ui/header/header'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{' '}
				<Header />
				<div className='bg-gradient-to-b from-[#EEF5FF] via-[#F8F4FF] to-[#FFFFFF]'>
					<Container>{children}</Container>
				</div>
			</body>
		</html>
	)
}
